### ISSUE TITLE
AttributeError: module 'tensorflow_core.python.keras.api._v2.keras.initializers' has no attribute 'random_normal'

### ISSUE THREAD

**Issue by karthikkrishnanv** [uber/ludwig#566]
**Describe the bug**
I am trying to setup ludwig + horovod combination and am hitting an old issue.

**Environment (please complete the following information):**
 - OS: Ubuntu
- Python version 3.6.8
- Ludwig version 0.2.1

pip3 list |grep tensorflow
bert-tensorflow      1.0.1      
tensorflow           1.14.0     
tensorflow-estimator 1.14.0     
tensorflow-gpu       2.0.0   

pip3 list | grep Keras
Keras                2.3.1      
Keras-Applications   1.0.8      
Keras-Preprocessing  1.1.0      

pip3 list | grep ludwig
ludwig               0.2.1      

The error says AttributeError: module 'tensorflow_core.python.keras.api._v2.keras.initializers' has no attribute 'random_normal'. One of the posts suggest tensorflow 1.12.0, however the latest ludwig says 1.14.0 is needed. Has anyone see this happen with the latest build ? It would be super helpful to have a Dockerfile that pulls all the supported bits for setting up ludwig + horovod specifically Cuda version.

**Comment by msaisumanth** [comment]
@karthikkrishnanv Ludwig doesn't work with tensorflow 2.0 yet. Please try with tf-gpu 1.14

**Comment by karthikkrishnanv** [comment]
That helped. Thanks! Made some progress, but it is crashing now with some MPI error. 
pip list |grep mpi
mpi4py               3.0.3 

MPI was via standard package manager (sudo apt-get install mpich) on ubuntu.
mpiexec --version
mpiexec (OpenRTE) 4.0.0

Are there any specific version dependencies w/ MPI ? Snipped error below

1,2]<stdout>:Loading data from: valid.hdf5
[1,1]<stdout>:Loading data from: valid.hdf5
[1,3]<stdout>:Loading data from: valid.hdf5
[1,0]<stdout>:Loading data from: valid.hdf5
[1,1]<stdout>:Loading data from: test.hdf5
[1,2]<stdout>:Loading data from: test.hdf5
[1,3]<stdout>:Loading data from: test.hdf5
[1,0]<stdout>:Loading data from: test.hdf5
[1,2]<stderr>:[60f0fdbbfa41:00101] *** Process received signal ***
[1,2]<stderr>:[60f0fdbbfa41:00101] Signal: Segmentation fault (11)
[1,2]<stderr>:[60f0fdbbfa41:00101] Signal code: Address not mapped (1)
[1,2]<stderr>:[60f0fdbbfa41:00101] Failing at address: 0x440000e9
[1,2]<stderr>:[60f0fdbbfa41:00101] [ 0] [1,2]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f8874208f20]
[1,2]<stderr>:[60f0fdbbfa41:00101] [ 1] [1,2]<stderr>:/usr/local/lib/libmpi.so.40(PMPI_Comm_set_errhandler+0x43)[0x7f877678f5c3]
[1,2]<stderr>:[60f0fdbbfa41:00101] [ 2] /usr/local/lib/python3.6/dist-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so(+0x81aef)[0x7f87d5dfeaef]

**Comment by karthikkrishnanv** [comment]
Thanks! That worked. I made some progress, but still getting a crash related to MPI.  Error snippet below. Are there any MPI version dependencies that could cause this ?

pip list | grep mpi
mpi4py               3.0.3 

mpichversion 
MPICH Version:    	3.3a2
MPICH Release date:	Sun Nov 13 09:12:11 MST 2016
MPICH Device:    	ch3:nemesis
MPICH configure: 	--build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --with-libfabric --enable-shared --prefix=/usr --enable-fortran=all --disable-rpath --disable-wrapper-rpath --sysconfdir=/etc/mpich --libdir=/usr/lib/x86_64-linux-gnu --includedir=/usr/include/mpich --docdir=/usr/share/doc/mpich --with-hwloc-prefix=system --enable-checkpointing --with-hydra-ckpointlib=blcr CPPFLAGS= CFLAGS= CXXFLAGS= FFLAGS= FCFLAGS=
MPICH CC: 	gcc  -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -Wformat -Werror=format-security  -O2
MPICH CXX: 	g++  -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -Wformat -Werror=format-security -O2
MPICH F77: 	gfortran  -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -O2
MPICH FC: 	gfortran  -g -O2 -fdebug-prefix-map=/build/mpich-O9at2o/mpich-3.3~a2=. -fstack-protector-strong -O2
MPICH Custom Information: 	

mpiexec --version
mpiexec (OpenRTE) 4.0.0


----------------------------

1,0]<stdout>:Found hdf5 and json with the same filename of the csvs, using them instead.
[1,0]<stdout>:Using hdf5 and json
[1,0]<stdout>:Loading data from: train.hdf5
[1,2]<stdout>:Loading metadata from: train.json
[1,1]<stdout>:Loading metadata from: train.json
[1,3]<stdout>:Loading metadata from: train.json
[1,0]<stdout>:Loading metadata from: train.json
[1,2]<stdout>:Loading data from: valid.hdf5
[1,1]<stdout>:Loading data from: valid.hdf5
[1,3]<stdout>:Loading data from: valid.hdf5
[1,0]<stdout>:Loading data from: valid.hdf5
[1,2]<stdout>:Loading data from: test.hdf5
[1,1]<stdout>:Loading data from: test.hdf5
[1,3]<stdout>:Loading data from: test.hdf5
[1,0]<stdout>:Loading data from: test.hdf5
[1,0]<stdout>:Training set: 32164
[1,0]<stdout>:Validation set: 4753
[1,0]<stdout>:Test set: 8207
[1,2]<stderr>:[87f16edb29cb:00102] *** Process received signal ***
[1,2]<stderr>:[87f16edb29cb:00102] Signal: Segmentation fault (11)
[1,2]<stderr>:[87f16edb29cb:00102] Signal code: Address not mapped (1)
[1,2]<stderr>:[87f16edb29cb:00102] Failing at address: 0x440000e9
[1,2]<stderr>:[87f16edb29cb:00102] [ 0] [1,2]<stderr>:/lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x7f7c2a0cdf20]
[1,2]<stderr>:[87f16edb29cb:00102] [ 1] [1,2]<stderr>:/usr/local/lib/libmpi.so.40(PMPI_Comm_set_errhandler+0x43)[0x7f7b2c6bc5c3]
[1,2]<stderr>:[87f16edb29cb:00102] [ 2] [1,2]<stderr>:/usr/local/lib/python3.6/dist-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so(+0x81aef)[0x7f7b8bd2baef]
[1,2]<stderr>:[87f16edb29cb:00102] [ 3] /usr/local/lib/python3.6/dist-packages/mpi4py/MPI.cpython-36m-x86_64-linux-gnu.so(+0x2e0c5)[0x7f7b8bcd80c5]
[1,2]<stderr>:[87f16edb29cb:00102] [ 4] [1,1]<stderr>:[87f16edb29cb:00101] *** Process received signal ***
[1,1]<stderr>:[87f16edb29cb:00101] Signal: Segmentation fault (11)
[1,1]<stderr>:[87f16edb29cb:00101] Signal code: Address not mapped (1)
[1,1]<stderr>:[87f16edb29cb:00101] Failing at address: 0x440000e9
[1,2]<stderr>:/usr/local/bin/python(PyModule_ExecDef+0x14b)[0x56667b]
[1,2]<stderr>:[87f16edb29cb:00102] [ 5] [1,2]<stderr>:/usr/local/bin/python[0x4fb884]
[1,2]<stderr>:[87f16edb29cb:00102] [ 6] [1,2]<stderr>:/usr/local/bin/python(PyCFunction_Call+0xd5)[0x567375]
[1,2]<stderr>:[87f16edb29cb:00102] [ 7] [1,2]<stderr>:/usr/local/bin/python(_PyEval_EvalFrameDefault+0x54af)[0x5115af]
[1,2]<stderr>:[87f16edb29cb:00102] [ 8] [1,2]<stderr>:/usr/local/bin/python[0x5081d5]
[1,2]<stderr>:[87f16edb29cb:00102] [ 9] [1,2]<stderr>:/usr/local/bin/python[0x50a020]
[1,2]<stderr>:[87f16edb29cb:00102] [10] [1,2]<stderr>:/usr/local/bin/python[0x50aa1d]
[1,2]<stderr>:[87f16edb29cb:00102] [11] [1,2]<stderr>:/usr/local/bin/python(_PyEval_EvalFrameDefault+0x449)[0x50c549]
[1,2]<stderr>:[87f16edb29cb:00102] [12] [1,2]<stderr>:/usr/local/bin/python[0x509ce8]
[1,2]<stderr>:[87f16edb29cb:00102] [13] /usr/local/bin/python[0x50aa1d]
[1,2]<stderr>:[87f16edb29cb:00102] [14] [1,2]<stderr>:/usr/local/bin/python(_PyEval_EvalFrameDefault+0x449)[0x50c549]
[1,2]<stderr>:[87f16edb29cb:00102] [15] [1,1]<stderr>:[87f16edb29cb:00101] [

**Comment by msaisumanth** [comment]
I'm not sure. Could you check if you are able to import tensorflow?

**Comment by karthikkrishnanv** [comment]
I reinstalled everything from scratch and it is working now. Closing this as the issue is not reproducible.

**Comment by w4nderlust** [comment]
Glad you solved it.

**Comment by Paladinhanxiao** [comment]
Is there any other solution, without replacing tf?

**Comment by w4nderlust** [comment]
Not sure wat you mean by replacing TF. You just ave to install the correct version listed in the set of requirements.
